library identifier: 'delphix_pipeline@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/pioro/delphix_pipeline.git']
)

pipeline {

   environment { 
        DLPX_ENGINE = "myengine1"
        DLPX_USER = "admin"
        DLPX_PASSWORD = "delphix"
        DXTOOLKIT_CONF = "/config/dxtools.conf"
   }
    
   agent {
      docker {
            image 'pioro/dxtoolkit:2.4.8'
            args '-u root -w /dxtoolkit -v ${PWD}:/config'
            reuseNode true
      }
   }

   stages {

      stage('Configure Engine') {
         steps {
            engine()
         }
      }


      stage('Discover environment') {
             steps {
                add_environment name:"source", host:"source", username:"oracle", password:"oracle"
             }
       }

      stage('Add dsource') {
         steps {
            create_dsource dbname:"test19", env:"source"
         }
      }
      
   }
}

